<a href="https://colab.research.google.com/github/kamwele/GDA_Live_coding_FML23/blob/main/John_mutinda__Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## what is Numpy

Numpy (Numerical Python) is an open source Python library that is used for arrays manipulations. It can be used to store data in one, two, three, ..., n dimensional arrays

## Difference between numpy and python list:

* numpy arrays store only data with same type however list can store different types of data

* lists consumes more memory for storage than numpy which lead it to be slower.
* Numpy uses contiguous memory and lists does not


##Intall Numpy

In [ ]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


## Import Numpy

In [ ]:
import numpy as np

## create arrays with numpy

In [ ]:
#create 1D numpy array


In [ ]:

#create 2D numpy arrays

In [ ]:
# create 3D array

## Dimension, shapes and types

In [ ]:
#Dimension

In [ ]:
#shape

In [ ]:
#types

## Accessing elements in numpy array (indexing and slicing)

---



In [ ]:
A = np.array([[1,2,3],[4,5,6]])
A.shape
b=np.array([[1,2],[2,4]])
b
b.shape

(2, 2)

In [ ]:
len(b)

2

In [ ]:
type(b)

numpy.ndarray

In [ ]:
b.ndim

2

In [ ]:
#SIZE
b.size

4

In [ ]:
#indexing

In [ ]:
C=np.array([[1,2,3],[4,5,6],[7,8,9]])
C
C.ndim

2

In [ ]:
type(C.ndim)

int

In [ ]:
C.dtype

dtype('int64')

In [ ]:
#slicing

In [ ]:
X=np.array([[1,2,3],[4,5,6]])
X
X[0:2,1:3]

array([[2, 3],
       [5, 6]])

##Exercise:

Write a code using slicing to reverse a numpy 1D array


In [ ]:
X[:,1:]

array([[2, 3],
       [5, 6]])

In [ ]:
x = np.array([1,2,3])
x[::-1]
## code here

array([3, 2, 1])

In [ ]:
np.flip(x,0)

array([3, 2, 1])

# Boolean or “mask” index arrays
#### Boolean arrays used as indices are treated in a different manner entirely than index arrays. Boolean arrays must be of the same shape as the initial dimensions of the array being indexed. In the most straightforward case, the boolean array has the same shape:

In [ ]:
y = np.array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
y<=80

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
n=0
n>-9

True

In [ ]:
np.where((y>10) & (y<18),-1,y)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, -1],
       [-1, -1, -1, -1],
       [-1, -1, 18, 19]])

In [ ]:
y>15

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [ True,  True,  True,  True]])

## np.where()

In [ ]:
#replace all values in y that are > 15 by -1 using np.where


## Exercise:

Replace all even numbers in the given array with -1 using np.where

In [ ]:
#write answer here
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np.where(x%2==0,-1,x)

array([-1,  1, -1,  3, -1,  5, -1,  7, -1,  9])

## Initializing arrays

In [ ]:
#create matrix with only ones
np.zeros((3,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Ex:

Write a code to create a numpy zero vector of size 10 and update element at index 5 and 6 with values to 10 and 11



In [ ]:
## code here
c=np.zeros((10,1))
c[5]=10
c[6]=11
c

array([[ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [10.],
       [11.],
       [ 0.],
       [ 0.],
       [ 0.]])

##Ex:

Write a NumPy program to create a 2d array with 1 on the border and 0 inside

In [ ]:
## code here
J=np.ones((8,9))
J[1:-1,1:-1]=0
J


array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
np.full((5,5),4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [ ]:
np.random.randint(6)

1

In [ ]:
np.random.rand(2,3)

array([[0.25491083, 0.29384754, 0.81449867],
       [0.02617694, 0.34706368, 0.52084011]])

In [ ]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [ ]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [ ]:
np.linspace(0,8)

array([0.        , 0.16326531, 0.32653061, 0.48979592, 0.65306122,
       0.81632653, 0.97959184, 1.14285714, 1.30612245, 1.46938776,
       1.63265306, 1.79591837, 1.95918367, 2.12244898, 2.28571429,
       2.44897959, 2.6122449 , 2.7755102 , 2.93877551, 3.10204082,
       3.26530612, 3.42857143, 3.59183673, 3.75510204, 3.91836735,
       4.08163265, 4.24489796, 4.40816327, 4.57142857, 4.73469388,
       4.89795918, 5.06122449, 5.2244898 , 5.3877551 , 5.55102041,
       5.71428571, 5.87755102, 6.04081633, 6.20408163, 6.36734694,
       6.53061224, 6.69387755, 6.85714286, 7.02040816, 7.18367347,
       7.34693878, 7.51020408, 7.67346939, 7.83673469, 8.        ])

In [ ]:
# create matrix with random values sampled from a normal distribution(np.random.randn)


In [ ]:
# create matrix with random int values from 0 to 10(np.random.randint)


In [ ]:
## create identity matrix(np.identity)


In [ ]:
## create matrix containing numbers from 0 to 10(np.arange)


In [ ]:
## create matrix containing even numbers from 0 to 10(np.arange)


### *When arange is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use the function linspace that receives as an argument the number of elements that we want, instead of the step:*

In [ ]:
#create an array of 8 elements between 0 and 3(np.linspace)
np.linspace(0,3,8).reshape(4,2)


array([[0.        , 0.42857143],
       [0.85714286, 1.28571429],
       [1.71428571, 2.14285714],
       [2.57142857, 3.        ]])

#Ex:

Write a code to create a numpy 3x3 matrix with values ranging from 2 to 10. 

In [ ]:
np.arange(2,11).reshape(3,3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

## Copying matrix

In [ ]:
a = np.array([1,2,3,4])

#copy a in b
b = a
b[0] = 10


In [ ]:
b

array([10,  2,  3,  4])

In [ ]:
a

array([10,  2,  3,  4])

In [ ]:
a = np.array([1,2,3,4])
b = a.copy()
b[0] = 10
b

array([10,  2,  3,  4])

## Math and numpy

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum

print(np.add(x,y))



# Elementwise difference
print(np.subtract(x,y))

# Elementwise product

print(np.multiply(x,y))
print(np.divide(x,y))

# Elementwise division


[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y=np.array([2,3])
np.add(x,y)
np.subtract(x,y)


array([[-1., -1.],
       [ 1.,  1.]])

\* is elementwise multiplication, not matrix multiplication. .dot function is used to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

## vector product, v and w
print(np.dot(v,w))

# Matrix / vector product, x and v
print(np.dot(x,v))

# Matrix / matrix product, x and y
print(np.dot(x,y))

219
[29 67]
[[19 22]
 [43 50]]


In [ ]:
x = np.array([[1,2],[3,4]])
print(np.sum(x,0))
 # Compute sum of all elements
print(np.sum(x))
  # Compute sum of each column
print(np.sum(x,1))
# Compute sum of each row

[4 6]
10
[3 7]


In [ ]:
x = np.array([[1,2],[3,4]])

# Compute the mean of all elements
np.mean(x)
  # Compute mean of each column
print(np.mean(x,0))

print(np.mean(x,1))
 # Compute mean of each row

[2. 3.]
[1.5 3.5]


In [ ]:
x = np.array([[1,2],[3,4]])

# Compute std of all elements
print(np.std(x))
# Compute std of each column
print(np.std(x,0))
# Compute std of each row
print(np.std(x,1))
pass

1.118033988749895
[1. 1.]
[0.5 0.5]


In [ ]:
x = np.array([1,2,3,4]) # each value is considered as an angle
#cos and sin of x

## Exercises:

Calculate the sum of the diagonal elements of a NumPy array using np.trace() and np.diagonal

In [ ]:

u = np.array([[1,2,3], [4,5,6], [7,8,9]])
u
np.sum(np.diagonal(u))

15

In [ ]:
np.trace(u)


15

## Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations.

Two arrays can be broadcasted if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.

In [ ]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
v = np.array([1, 0, 1])
print(x.shape)
print(v.shape)
y = x * v  # Add v to each row of x using broadcasting
print(y)
print("=="*10)
w = np.array([[1], [0], [1]])
print(w.shape)
print(x+w)

(3, 3)
(3,)
[[1 0 3]
 [4 0 6]
 [7 0 9]]
(3, 1)
[[ 2  3  4]
 [ 4  5  6]
 [ 8  9 10]]


In [ ]:
v = np.array([1,2,3]) 
w = np.array([4,5])   
print(v.shape)
print(w.shape) 
#we need to reshape v to be a column vector of shape (3, 1); we can then broadcast it against w 
y = v.reshape(3,1) * w
print(y)
print(y.shape)


(3,)
(2,)
[[ 4  5]
 [ 8 10]
 [12 15]]
(3, 2)


## Numpy and linear algebra

In [ ]:
x = np.random.randint(0, 20, 10)
x
np.linalg.norm(x,np.inf)

19.0

### Norm:

In [ ]:
#compute norm of x

In [ ]:
#compute norm 1 of x

In [ ]:
#compute norm 2 of x

### Eigen values and vectors

In [ ]:

x = np.random.randint(0, 20, (3,3))
#compute the eigen values of x
np.linalg.eigh(x)
np.linalg.eigvals(x)
np.linalg.eigh(x)

(array([-9.62561934, 12.02122856, 31.60439077]),
 array([[ 0.48309012,  0.50439787,  0.7156862 ],
        [ 0.17365313, -0.85635174,  0.48631912],
        [-0.85817745,  0.11065481,  0.50128533]]))

### determinant

In [ ]:
#compute determinant of x


### Inverse matrix

In [ ]:
#compute the inverse matrix of x


## More in Numpy

https://numpy.org/doc/stable/user/absolute_beginners.html

https://realpython.com/numpy-tutorial  